name: benevolix_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  http: ^1.3.0
  shared_preferences: ^2.0.6
  flutter_riverpod: ^2.6.1
  dio: ^5.8.0+1
  freezed_annotation: ^3.0.0
  font_awesome_flutter: ^10.8.0
  flutter_secure_storage: ^4.2.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  freezed: ^3.0.4
  json_serializable: ^6.7.1

  flutter_lints: ^5.0.0


flutter:

 
  uses-material-design: true

  assets:
    - assets/images/Benevolix.png
    - assets/images/home_icon.png
    - assets/images/user_icon.png
    - assets/images/close.png
    - assets/images/date_icon.png
    - assets/images/place_icon.png
    - assets/images/hashtag_icon.png
    - assets/images/sablier_icon.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

